### ISSUE TITLE
As IDM user I want to see correctly Location and Skiarea dataset,

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-databrowser#750]
As mentionded by Antonietta, there is no way to see any details about the following dataset:

- [ ] Location - https://databrowser.opendatahub.com/dataset/table/tourism/v1/Location
- [ ] Skiarea (but Ski area works) - https://databrowser.opendatahub.com/dataset/table/tourism/v1/Location/Skiarea

As you can see from the screenshots below, the DataBrowser shows an empty table while entering to the dataset.

**Location**
![Image](https://github.com/user-attachments/assets/79260662-d1d9-49c7-b698-451ec3c42dde)

**Skiareas**
![Image](https://github.com/user-attachments/assets/3ccd0bdd-667d-483c-945a-63ecc7e92fea)

**Comment by sseppi** [comment]
@RudiThoeni If I got it right, it could be that the issue is the same as the issue #749 . this means that the issue could be solved by adding the pagination also to this endpoints.

Do I'm right?

**Comment by gappc** [comment]
@sseppi @RudiThoeni I think the issue may be related to a bug in the "generated config" algorithm as mentioned here: https://github.com/noi-techpark/opendatahub-databrowser/issues/744#issuecomment-2873256208

**Comment by gappc** [comment]
@sseppi @RudiThoeni I've created issue #757 to fix the bug in the generated view. I think we can close this issue here, because it should be resolved by #757.

**Comment by sseppi** [comment]
@RudiThoeni I still have the same problem to see the Location in testing, did you already merged the fix?

**Comment by RudiThoeni** [comment]
no because https://github.com/noi-techpark/opendatahub-databrowser/pull/758 it is defined as work in progress can i merge it @gappc

**Comment by sseppi** [comment]
Probably it was a cache problem, now it works for me too. I put this issue in toReview, so we know that it can be reviewed also by Antonietta.
